---
# Base config file for snippets #
# This file is read for default parameters but 
# if this file specifies a snippet library that
# contains a valid lesson configuration file
# the lesson snippets file is used instead
# this file has been cleared because directives are overridden by the 
# file specified "snippets" directive


local:

# snippet library - should match a directory under episodes/files/snippets/
snippets: NCL_Comet_slurm

# base URL for lesson website (?overridden by above?)
baseurl: "https://NewcastleRSE-Training.github.io/probable-pancake/"
